// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0fgwCRIY6LMz0q_t88OVV0ih0mRPqHwI',
    appId: '1:378447833677:web:ff08330c421522b31e8a04',
    messagingSenderId: '378447833677',
    projectId: 'lab3-ee0c1',
    authDomain: 'lab3-ee0c1.firebaseapp.com',
    storageBucket: 'lab3-ee0c1.firebasestorage.app',
    measurementId: 'G-VWBNG7DV44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsN_VqknExDDDZLBwg8TkEF4hVtRtXaqg',
    appId: '1:378447833677:android:93496311c5f3cbe61e8a04',
    messagingSenderId: '378447833677',
    projectId: 'lab3-ee0c1',
    storageBucket: 'lab3-ee0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibPBQEizSatsn_xSHx86UFK_STO1pa0k',
    appId: '1:378447833677:ios:5ef412a0da3fa1ec1e8a04',
    messagingSenderId: '378447833677',
    projectId: 'lab3-ee0c1',
    storageBucket: 'lab3-ee0c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibPBQEizSatsn_xSHx86UFK_STO1pa0k',
    appId: '1:378447833677:ios:5ef412a0da3fa1ec1e8a04',
    messagingSenderId: '378447833677',
    projectId: 'lab3-ee0c1',
    storageBucket: 'lab3-ee0c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0fgwCRIY6LMz0q_t88OVV0ih0mRPqHwI',
    appId: '1:378447833677:web:ee35ce073daf99191e8a04',
    messagingSenderId: '378447833677',
    projectId: 'lab3-ee0c1',
    authDomain: 'lab3-ee0c1.firebaseapp.com',
    storageBucket: 'lab3-ee0c1.firebasestorage.app',
    measurementId: 'G-8XHTJ1EFD3',
  );
}
